# Generated by Django 5.0.1 on 2024-06-07 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trouble_app', '0003_alter_issue_assigned_to_alter_issue_resolved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='created_at',
        ),
        #migrations.RemoveField(
         #   model_name='issue',
         #   name='resolved_by',
        #),
        migrations.RemoveField(
            model_name='issue',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
