# Generated by Django 5.0.1 on 2024-06-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trouble_app', '0004_remove_issue_created_at_remove_issue_resolved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='resolved_by',
        ),
    ]
